# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitscrum" do
  name "gitscrum"
  desc "GitScrum CLI - Project Management from your terminal"
  homepage "https://gitscrum.com"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitscrum"
  bash_completion "completions/gitscrum.bash"
  zsh_completion "completions/_gitscrum"
  fish_completion "completions/gitscrum.fish"

  on_macos do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_amd64.tar.gz"
      sha256 "581a89a3da9ea57798172cee562278bd5458023bdc3563b6af3452629158e378"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_arm64.tar.gz"
      sha256 "9c1b0e116b87c01c63e43ca68159ca2c61e530b3253590562a3975dc9d31d1fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_amd64.tar.gz"
      sha256 "3eeda0ae5552fec7dcc5f75a9021be7f128ca403d64065423a0c2b2eee8d82cf"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_arm64.tar.gz"
      sha256 "f8911a00e03ca407d396bcd7eead91de85be67a825499480ff7e896902befe94"
    end
  end

  # No zap stanza required
end
