# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitscrum" do
  name "gitscrum"
  desc "GitScrum CLI - Project Management from your terminal"
  homepage "https://gitscrum.com"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitscrum"
  bash_completion "completions/gitscrum.bash"
  zsh_completion "completions/_gitscrum"
  fish_completion "completions/gitscrum.fish"

  on_macos do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_amd64.tar.gz"
      sha256 "d503a5fde95120f9615cb0a4bf0c1259388dc07ba5dc375c18261295f4b95554"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_arm64.tar.gz"
      sha256 "26409b7859cfa0acb84dbd5b0c6c37bec8431dd8336c744b70288903bd2e3595"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_amd64.tar.gz"
      sha256 "8d6a3c23c30bd820c271f64c6eac6bbe0204febee0ada16e3d991013a6f04229"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_arm64.tar.gz"
      sha256 "bc8661196351384eed56b41889f4ca1b03c966a52740492eb855ca1dbe9eb7e7"
    end
  end

  # No zap stanza required
end
