# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitscrum" do
  name "gitscrum"
  desc "GitScrum CLI - Project Management from your terminal"
  homepage "https://gitscrum.com"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitscrum"
  bash_completion "completions/gitscrum.bash"
  zsh_completion "completions/_gitscrum"
  fish_completion "completions/gitscrum.fish"

  on_macos do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_amd64.tar.gz"
      sha256 "51c5f88d7ab7fd1251e4ad1331e913b94181fccc3b348d7aa53194c84025d517"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_darwin_arm64.tar.gz"
      sha256 "1fb1f7c7e5e846a6f2732d7cb138f863a413056918a0a2e9abc85d4c47881af0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_amd64.tar.gz"
      sha256 "6cb32fcec48e72800f4bfee3c4e23f41ab695dafe2aacb5e76aaa58b279abab9"
    end
    on_arm do
      url "https://github.com/gitscrum-core/cli/releases/download/v#{version}/gitscrum_#{version}_linux_arm64.tar.gz"
      sha256 "b91b66f3f3a41fe2e62e5b0644fe74ab5c1ffd28503675f396c64ef0c7dbf517"
    end
  end

  # No zap stanza required
end
